%YAML:1.0
# data
# walking people: rgbd_dataset_freiburg3_walking_xyz
# sitting people: rgbd_dataset_freiburg3_sitting_static
dataset_dir: /home/buyi/Datasets/rgbd_dataset_freiburg3_sitting_static

# camera intrinsics
# fr1
Camera.fx: 517.3
Camera.fy: 516.5
Camera.cx: 325.1
Camera.cy: 249.7

Camera.width: 640
Camera.height: 480

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

Camera.depth_scale: 5000

# VO Parameters
Camera.PyraLevels: 5
Camera.CellSize: 30
Camera.Max_fts: 200


#Rarsac algorithm
Rarsac.Threshold: 0.75
Rarsac.MaxIterators: 1000