%YAML:1.0
# data
# walking people: rgbd_dataset_freiburg3_walking_xyz
# sitting people: rgbd_dataset_freiburg3_sitting_static
#rgbd_dataset_freiburg2_desk_with_person
#rgbd_dataset_freiburg3_walking_static
dataset_dir: /home/buyi/Datasets/longhouse

Camera.width: 640
Camera.height: 480

# camera intrinsics
# fr1
#Camera.fx: 517.3
#Camera.fy: 516.5
#Camera.cx: 325.1
#Camera.cy: 249.7

#Camera.k1: 0.2624
#Camera.k2: -0.9531
#Camera.p1: -0.0054
#Camera.p2: 0.0026
#Camera.k3: 1.1633

# fr2
#Camera.fx: 520.9
#Camera.fy: 521.0
#Camera.cx: 325.1
#Camera.cy: 249.7

#Camera.k1: 0.231222
#Camera.k2: -0.784899
#Camera.p1: -0.003257
#Camera.p2: -0.000105
#Camera.k3: 0.917205

# fr3
Camera.fx: 535.4
Camera.fy: 539.2
Camera.cx: 320.1
Camera.cy: 247.6

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.f: 525

Camera.depth_scale: 5000

# VO Parameters
Camera.MaxPyraLevels: 5
Camera.MinPyraLevels: 0
Camera.CellSize: 30
Camera.Max_fts: 400
Camera.Min_fts: 15
Camera.Min_dist: 30

Camera.Half_PatchSize: 4


#Rarsac algorithm
Rarsac.Sampson_Dist_threshold: 1.25
Rarsac.MaxIterators: 1000
Rarsac.Terminate_threshold: 0.001

#Ceres optimization
Optimization.MaxIter: 8

#Insert KeyFrame
KeyFrame.min_rot: 0.04
KeyFrame.min_trans: 0.04
KeyFrame.min_features: 25
KeyFrame.min_dist: 0.12