%YAML:1.0
# data
dataset_dir: /home/buyi/Datasets/EuRoC/mav0/cam0

# camera intrinsics
# fr1
Camera.fx: 458.654
Camera.fy: 457.296
Camera.cx: 367.215
Camera.cy: 248.375

Camera.width: 752
Camera.height: 480

# fr2
Camera.k1: -0.28368365
Camera.k2: 0.07451284
Camera.p1: -0.00010473
Camera.p2: -3.55590700e-05
Camera.k3: 0.0

camera.depth_scale: 5000

# Feature Detection
Camera.PyraLevels: 3
Camera.CellSize: 30
Camera.Max_fts: 200
Camera.Min_dist: 30


#Rarsac algorithm
Rarsac.Sampson_Dist_threshold: 1.25
Rarsac.MaxIterators: 2000
Rarsac.Terminate_threshold: 0.001

#Ceres optimization
Optimization.MaxIter: 8

#Insert KeyFrame
KeyFrame.min_rot: 0.04
KeyFrame.min_trans: 0.04
KeyFrame.min_features: 25