%YAML:1.0
# data
dataset_dir: /home/buyi/Datasets/EuRoC/mav0/cam0

# camera intrinsics
# fr1
Camera.fx: 458.654
Camera.fy: 457.296
Camera.cx: 367.215
Camera.cy: 248.375

Camera.width: 752
Camera.height: 480

# fr2
#camera.fx: 520.9
#camera.fy: 521.0
#camera.cx: 325.1
#camera.cy: 249.7

camera.depth_scale: 5000

# VO Parameters
Camera.PyraLevels: 5
Camera.CellSize: 30
Camera.Max_fts: 200


#Rarsac algorithm
Rarsac.Threshold: 1.25
Rarsac.MaxIterators: 1000