%YAML:1.0
# data
# walking people: rgbd_dataset_freiburg3_walking_xyz
# sitting people: rgbd_dataset_freiburg3_sitting_static
#rgbd_dataset_freiburg2_desk_with_person
#rgbd_dataset_freiburg3_walking_static
dataset_dir: /home/buyi/Datasets/SVO/sin2_tex2_h1_v8_d

Camera.width: 752
Camera.height: 480

# camera intrinsics
Camera.fx: 315.5
Camera.fy: 315.5
Camera.cx: 376.0
Camera.cy: 240.0

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.f: 315.5

Camera.depth_scale: 1

# VO Parameters
Camera.MaxPyraLevels: 5
Camera.MinPyraLevels: 0
Camera.CellSize: 30
Camera.Max_fts: 300
Camera.Max_tkfts: 200
Camera.Min_fts: 15
Camera.Min_dist: 30

Camera.Half_PatchSize: 4

# Viewer
Camera.fps: 30
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3


#Rarsac algorithm
Rarsac.Sampson_Dist_threshold: 1.25
Rarsac.MaxIterators: 1000
Rarsac.Terminate_threshold: 0.001

#Ceres optimization
Optimization.MaxIter: 8

#Insert KeyFrame
KeyFrame.min_rot: 0.04
KeyFrame.min_trans: 0.04
KeyFrame.min_features: 25